# http://travis-ci.org/#!/jupyter/jupyterhub
language: python
sudo: false
python:
  - 3.7-dev
  - 3.6
  - 3.5
  - 3.4
install:
  - pip install pbr wheel
  - python setup.py bdist_wheel
  - pip install dist/*.whl -r dev-requirements.txt
script:
  - py.test --cov=hubshare hubshare/tests -v
after_success:
  - codecov
